[features]
seeds = true
skip-lint = false
[programs.localnet]
anchor_nft_staking = "9LBrnLemZ4GB16zh1ChJtVFh7xrrSxtVBxVCT8BC8nJB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ghazzog/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
